vich_uploader:
  db_driver: orm
  mappings:
    gite_image:
      uri_prefix: /images/gites
      upload_destination: "%kernel.project_dir%/public/images/gites"
      namer: Vich\UploaderBundle\Naming\UniqidNamer

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
